#
# Configuration for the Ollivanders2 plugin.
#
chatDropoff: 50
witchDrop: false
divination: true
divinationBlock: 20
divinationMaxDuration: 86400000
divinationMaxStartOffset: 604800000
muggletonBlockChange: true
#
# When death exp loss is enabled, players will lose their spell experience if they die.  It is not recommended to set
# this to true if your server supports minigames or other plugins that expect players will die.
deathExpLoss: false
#
# When book learning is true, players can only cast spells they have learned from a book.  This prevents players
# being able to cast spells they have not "learned" but have seen in chat, etc.
bookLearning: true
#
spellJournal: true
#
# When nonVerbalSpellCasting is set to true, once players master a spell they can cast it without saying the incantation
nonVerbalSpellCasting: true
#
# When hostileMobAnimagi is set to true, the possible animagus forms will include hostile mobs such as spiders
hostileMobAnimagi: false
chatColor: 5
flooPowder: REDSTONE
broomstick: STICK
#
# When houses are enabled, Ollivanders will use the built-in minecraft scoreboard to create house teams and points.
# IMPORTANT: Enabling houses will take over your server's main scoreboard.  If you do not want this, you must
# set this to false.
houses: false
#
# If houses are enabled, you can change the name of them in the game by uncommenting and editing
# gryffindorName: Gryffindor
# hufflepuffName: Hufflepuff
# ravenclawName: Ravenclaw
# slytherinName: Slytherin
#
# If houses are enabled, you can change the color for player name tags and chat by uncommenting and editing
# Options are: WHITE, GRAY, RED, GOLD, YELLOW, GREEN, AQUA, BLUE, LIGHT_PURPLE, DARK_GRAY, DARK_RED, DARK_AQUA, DARK_BLUE, DARK_PURPLE
# gryffindorColor: DARK_RED
# hufflepuffColor: GOLD
# ravenclawColor: DARK_BLUE
# slytherinColor: DARK_GREEN
#
# When years is set to true, it enables the /olli year command
years: false
#
# Turns on debug output in your logs. This can also be done while the game is running by using the command
# /olli debug
debug: false
zones:
  default-world:
    type: World
    world: world
    allowed-spells:
      - 
    disallowed-spells:
      - 
  default-cuboid:
    type: Cuboid
    world: world
    area: 0 0 0 0 0 0
    allowed-spells:
      - 
    disallowed-spells:
      - 