update: true
chatDropoff: 50
witchDrop: false
divination: true
divinationBlock: 20
divinationMaxDuration: 86400000
divinationMaxStartOffset: 604800000
muggletonBlockChange: true
deathExpLoss: false
bookLearning: false
chatColor: 5
flooPowder: REDSTONE
broomstick: STICK
zones:
  default-world:
    type: World
    world: world
    allowed-spells:
      - 
    disallowed-spells:
      - 
  default-cuboid:
    type: Cuboid
    world: world
    area: 0 0 0 0 0 0
    allowed-spells:
      - 
    disallowed-spells:
      - 